# Generated by Django 3.2 on 2021-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210511_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('HR', 'HELP_REQUEST'), ('HO', 'HELP_OFFER')], default='HR', max_length=2),
        ),
    ]
